l_russian:
 setting_decision: "Discord AI: Настройки"
 sino_japanese_war_balance_sp: "Китайско-японское равновесие"
 LSM_equipment.31.t: "Китайско-японское равновесие"
 LSM_equipment.31.d: "Здесь может решиться исход китайско-японской войны."
 LSM_equipment.31.a: "Усиленный Китай"
 LSM_equipment.31.b: "Значительно усиленный Китай"
 LSM_equipment.31.c: "Для Японии пока ничего нет"
 LSM_setting_tt_CHI_1: "Китай будет ежемесячно получать базовое пехотное снаряжение"
 LSM_setting_tt_CHI_2: "(Наверное, для фарма опыта) Китай будет получать базовое пехотное снаряжение и пехотное снаряжение I каждый месяц, 1 пехотную дивизию и 3 пехотные дивизии с поддержкой артиллерии каждый раз, когда теряет новый регион."
 modifier_experience_gain_battle_cruiser_training_factor:1 "Бонус к получаемому опыту при обучении линейных крейсеров"
 modifier_experience_gain_battle_cruiser_mission_factor: "Бонус к опыту за миссии линейных крейсеров"
 modifier_experience_gain_battle_cruiser_combat_factor:1 "Бонус к боевому опыту линейных крейсеров"
 modifier_experience_gain_battleship_training_factor:1 "Бонус к получаемому опыту при обучении линкоров"
 modifier_experience_gain_battleship_mission_factor: "Бонус к опыту за миссии линкоров"
 modifier_experience_gain_battleship_combat_factor:1 "Бонус к боевому опыту линкоров"
 modifier_experience_gain_carrier_training_factor:1 "Бонус к получаемому опыту при обучении авианосцев"
 modifier_experience_gain_carrier_mission_factor: "Бонус к опыту за миссии авианосцев"
 modifier_experience_gain_carrier_combat_factor:1 "Бонус к боевому опыту авианосцев"
 modifier_experience_gain_destroyer_training_factor:1 "Бонус к получаемому опыту при обучении эсминцев"
 modifier_experience_gain_destroyer_mission_factor: "Бонус к опыту за миссии эсминцев"
 modifier_experience_gain_destroyer_combat_factor:1 "Бонус к боевому опыту эсминцев"
 modifier_experience_gain_heavy_cruiser_training_factor:1 "Бонус к получаемому опыту при обучении тяжелых крейсеров"
 modifier_experience_gain_heavy_cruiser_mission_factor: "Бонус к опыту за миссии тяжелых крейсеров"
 modifier_experience_gain_heavy_cruiser_combat_factor:1 "Бонус к боевому опыту тяжелых крейсеров"
 modifier_experience_gain_heavy_ship_training_factor:1 "Бонус к опыту при обучении сверхтяжелых линкоров"
 modifier_experience_gain_heavy_ship_mission_factor: "Бонус к опыту за миссии сверхтяжелых линкоров"
 modifier_experience_gain_heavy_ship_combat_factor:1 "Бонус к боевому опыту сверхтяжелых линкоров"
 modifier_experience_gain_light_cruiser_training_factor:1 "Бонус к опыту при обучении легких крейсеров"
 modifier_experience_gain_light_cruiser_mission_factor: "Бонус к опыту за миссии легких крейсеров"
 modifier_experience_gain_light_cruiser_combat_factor:1 "Бонус к боевому опыту легких крейсеров"
 modifier_experience_gain_submarine_training_factor:1 "Бонус к опыту при обучении подводных лодок"
 modifier_experience_gain_submarine_mission_factor: "Бонус к опыту за миссии подводных лодок"
 modifier_experience_gain_submarine_combat_factor:1 "Бонус к боевому опыту подводных лодок"